Portfolio creation
masouma2020/portfolio2 pull request #1
Opened 2022-08-25 13:15 UTC by masouma2020

This is the last part of a portfolio for moblie

2022-08-25 13:31 UTC, vechicin reviewed
# Hi @masouma2020 ✋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😞 

## Invalid Code Review Request ⚠️ 

You have submitted a project, that has failing linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-25 14:41 UTC, mwanawabangona requested changes
Hi @masouma2020 ,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 14:41 UTC, mwanawabangona commented on index.html
>              </div>
- [ ] `required`
- [ ] Great job so far 👏 
- [ ] However the list of project technologies are supposed to `ul` and each of them in a `li` see example `below`
![image](https://user-images.githubusercontent.com/66230306/186690799-18f92099-0f01-46bc-8bf3-46ea9828594f.png)
Kindly make amends on all the technologies

2022-08-25 14:41 UTC, mwanawabangona commented on index.html
>              </div>
- [ ] `required`
- [ ] Here as mentioned above 
- [ ] However the list of project technologies are supposed to `ul` and each of them in a `li` see example `below`
![image](https://user-images.githubusercontent.com/66230306/186690799-18f92099-0f01-46bc-8bf3-46ea9828594f.png)
Kindly make amends on all the technologies

2022-08-25 14:41 UTC, mwanawabangona commented on index.html
> +              <span id="d3">RUBY</span>
- [ ] `required`
- [ ] Here as mentioned above 
- [ ] However the list of project technologies are supposed to `ul` and each of them in a `li` see example `below`
![image](https://user-images.githubusercontent.com/66230306/186690799-18f92099-0f01-46bc-8bf3-46ea9828594f.png)
Kindly make amends on all the technologies

2022-08-25 14:41 UTC, mwanawabangona commented on index.html
>                </div>
- [ ] `required`
- [ ] Here as mentioned above 
- [ ] However the list of project technologies are supposed to `ul` and each of them in a `li` see example `below`
![image](https://user-images.githubusercontent.com/66230306/186690799-18f92099-0f01-46bc-8bf3-46ea9828594f.png)
Kindly make amends on all the technologies

2022-08-25 14:41 UTC, mwanawabangona commented on index.html
> +            <button type="reset">See Project</button>
- [ ] `required`
- [ ] Kindly add a hover on `all the buttons` `why?` so that someone is able to tell that its a button when they hover on

2022-08-25 16:47 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @masouma2020  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 00:51 UTC, merged

2022-08-26 00:51 UTC, masouma2020 commented
Complete the project